### ISSUE TITLE
Can this app auto change the label based on title?

### ISSUE THREAD

**Issue by evillt** [machine-learning-apps/Issue-Label-Bot#55]
Here's my facing problem. See https://github.com/evillt/saika/issues/43

Since I changed the title from `feat:xxx` to `fix:xxx`, and the label still is `feature_request`.

Maybe we can remove the `feature_request` then add `bug` or something.

**Comment by jlewi** [comment]
I think the label bot only takes action when the issue is created. We don't take action when an issue updated

I think we would need to fix that to change the label after title is updated. We would also have to improve the label bot so that it didn't do things like add back labels that had been explicitly removed.
